version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: and
        validate:
          - do: description
            no_empty:
              enabled: true
            and:
              - must_include:
                  regex: '\[[a-zA-Z]{2,6}-\d{1,7}\]'
                  regex_flag: none
              - must_include:
                  regex: '\[[a-zA-Z]{2,6}-\d{1,7}\]:\shttps:\/\/nextraq.+'
                  regex_flag: none
                  message: |
                    Jira bot expected to automagically link the ticket.
          - do: and
            validate:
              - do: or
                validate:
                  - do: title
                    must_include:
                      regex: feat|chore|fix
                      message: Custom message...
                  - do: title
                    must_include:
                      regex: '\[[a-zA-Z]{2,6}-\d{1,7}\]'
                      regex_flag: none
                      message: >
                        "Please include the jira ticket in the title (using the
                        format [AAA-123])."
              - no_empty:
                  enabled: true
                  
  - when: 'pull_request.*, issues.*'
    validate:
      - do: title
        must_exclude:
          regex: '^\[WIP\]'
      - do: label
        must_exclude:
          regex: WIP
    pass:
      - do: labels
        delete: WIP
    fail:
      - do: labels
        add: WIP
