version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: and
        validate:
        
        - do: description
          and:
            - or:
              - must_include:
                  regex: '\[[a-zA-Z]{2,6}-\d{1,7}\]'
                  regex_flag: none
              - must_include:
                  regex: '\[[a-zA-Z]{2,6}-\d{1,7}\]:\shttps:\/\/nextraq.+'
                  regex_flag: none
                  message: |
                    Jira bot expected to automagically link the ticket.
              - must_exclude:
                  regex: '### Issue Link :link:'
                  regex_flag: 'none'
            
            - no_empty:
                enabled: true
          
          - do: title
            or:
              - must_include:
                  regex: '\[[a-zA-Z]{2,6}-\d{1,7}\]'
                  regex_flag: none
                  message: >
                    "Please include the jira ticket in the title (using the
                    format [AAA-123])."
              - must_include:
                  regex: feat|chore|fix|ci|doc|perf
                  message: 'Titles should follow semantic release conventions.'
                  
  - when: 'pull_request.*, issues.*'
    validate:
      - do: title
        must_exclude:
          regex: '^\[WIP\]'
      - do: label
        must_exclude:
          regex: WIP
    pass:
      - do: labels
        delete: WIP
    fail:
      - do: labels
        add: WIP
