version: 2
mergeable:
- when: pull_request.*, pull_request_review.*
  validate:
  - do: description
    no_empty:
      enabled: true
    and:
    - must_include:
        regex: \[[a-zA-Z]{2,6}-\d{1,7}\]
        regex_flag: none
        message: >
          Please include ticket link in square brackets (ex: [AAA-123])
    - must_include:
        regex: \[[a-zA-Z]{2,6}-\d{1,7}\]:\shttps:\/\/nextraq.+
        regex_flag: none
        message: >
          Jira bot expected to automagically link the ticket.
  - do: title
    no_empty:
      enabled: true
    must_include:
      regex: \[[a-zA-Z]{2,6}-\d{1,7}\]
      regex_flag: none
      message: >
        Please include ticket in title in square brackets (ex: [AAA-123])

- when: pull_request.*, issues.*
  validate:
  - do: title
    must_exclude:
      regex: ^\[WIP\]
  - do: label
    must_exclude:
      regex: WIP
  pass:
  - do: labels
    labels: [WIP]
    mode: delete
  fail:
  - do: labels
    labels: [WIP]

- when: schedule.repository
  validate:
  - do: stale
    days: 20
    type: pull_request, issues
  pass:
  - do: comment
    payload:
      body: There hasn't been any activity for a while.  Is it still relevant?
